server:
  port: 9005
  
spring:
  application:
    name: feign-client-service
    
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    hostname: localhost
    
management:
  endpoint:
    serviceregistry:
      enabled: true  
    pause:
      enabled: true
       